# Site settings
name: Jiwon's Blog
email: awldnjs2@gmail.com
url: https://koreamarin.github.io/
description: "A blog and a portfolio"
author: "Jiwon Ryu"
title: "블로그"
permalink: pretty
baseurl: /
future: ture # true이면 현재 날짜 이후의 포스트글들도 보임, false이면 현재날짜 이후의 포스트글은 리스트에 보이지않음.

# social
github:
  username: koreamarin

twitter:
  username: username

comments:
  provider: "disqus"
  disqus:
    shortname: koreamarin.github.io
