# Site settings
name: Jiwon's Blog
email: awldnjs2@gmail.com
url: https://koreamarin.github.io/
description: "A blog and a portfolio"
author: "Jiwon Ryu"
title: "블로그"
permalink: pretty
baseurl: /

# social
github:
  username: koreamarin

twitter:
  username: username

comments:
  provider: "disqus"
  disqus:
    shortname: koreamarin.github.io
