# Site settings
name: Jiwon's Blog
email: awldnjs2@gmail.com
url: url
description: "A blog and a portfolio"
author: "Jiwon Ryu"
title: "BlogFolio"
permalink: pretty
baseurl: /

# social
github:
  username: koreamarin

twitter:
  username: username
